#!/bin/bash

[ -f $(dirname $0)/bash-wrapper-functions ] && .  $(dirname $0)/bash-wrapper-functions || { echo "[error]: $(dirname $0)/bash-wrapper-functions not found, the application was probably not installed correctly" 1>&2; exit 1; }

MAIN_CLASS=io.novaordis.jmx.cli.Main
JAVA_DEBUG_ARGS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"

function main() {

    local args
    local java_debug_args

    while [ -n "$1" ]; do

        if [ "$1" = "-d" -o "$1" = "--debug" ]; then
            java_debug_args="${JAVA_DEBUG_ARGS}"
        else
            args="${args} $1"
        fi

        shift
    done

    local java_bin
    java_bin=$(get-java-binary) || exit 1

    local classpath
    classpath=$(get-classpath-from-directory $(dirname $0)/../lib)

    ${java_bin} ${java_debug_args} -cp ${classpath} ${MAIN_CLASS} ${args}
}

main $@;

